### ISSUE TITLE
Możliwe wycieki pamięci

### ISSUE THREAD

**Issue by galczo5** [jBosak98/WUST-object-oriented-programming#1]
Masz w jednym pliku dynamiczny przydział pamięci a nie widzę nigdzie jej zwalniania.
https://github.com/jBosak98/WUST-object-oriented-programming/blob/05745db72094aae3748aa2c998010729512a6d85/3.complex.../Complex/complex.cpp#L57

Celowo tak?

**Comment by jBosak98** [comment]
Błąd naprawiono.
